### ISSUE TITLE
PyCharm complains about changes during undo

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#124]
Steps to reproduce:

1. Add a new Python file to your project.
2. Start live coding.
3. Type a single line: `s = 'hello world'`
4. Delete the word "world".
5. Type <kbd>Ctrl</kbd>+<kbd>Z</kbd>.

Expected result: the word "world" reappears.
Actual result: the word reappears, as well as an error notice:

```
Do not change documents during undo as it will break undo sequence.
java.lang.IllegalStateException: Do not change documents during undo as it will break undo sequence.
	at com.intellij.openapi.command.impl.DocumentUndoProvider$MyEditorDocumentListener.beforeDocumentChange(DocumentUndoProvider.java:70)
	at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy22.beforeDocumentChange(Unknown Source)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:756)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:722)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:595)
	at com.intellij.openapi.editor.impl.DocumentImpl.access$500(DocumentImpl.java:60)
	at com.intellij.openapi.editor.impl.DocumentImpl$6.run(DocumentImpl.java:1010)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.editor.impl.DocumentImpl.setText(DocumentImpl.java:1017)
	at io.github.donkirkby.livepycharm.LiveCodingAnalyst.lambda$documentChanged$0(LiveCodingAnalyst.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:934)
	at io.github.donkirkby.livepycharm.LiveCodingAnalyst.documentChanged(LiveCodingAnalyst.java:81)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:791)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:727)
	at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:485)
	at com.intellij.openapi.command.impl.EditorChangeAction.a(EditorChangeAction.java:104)
	at com.intellij.openapi.command.impl.EditorChangeAction.performUndo(EditorChangeAction.java:78)
	at com.intellij.openapi.command.impl.EditorChangeAction.undo(EditorChangeAction.java:65)
	at com.intellij.openapi.command.impl.UndoableGroup.a(UndoableGroup.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:934)
	at com.intellij.openapi.command.impl.UndoableGroup.a(UndoableGroup.java:124)
	at com.intellij.openapi.command.impl.UndoableGroup.c(UndoableGroup.java:112)
	at com.intellij.openapi.command.impl.UndoableGroup.undo(UndoableGroup.java:94)
	at com.intellij.openapi.command.impl.Undo.performAction(Undo.java:46)
	at com.intellij.openapi.command.impl.UndoRedo.execute(UndoRedo.java:143)
	at com.intellij.openapi.command.impl.CommandMerger.undoOrRedo(CommandMerger.java:217)
	at com.intellij.openapi.command.impl.UndoManagerImpl.a(UndoManagerImpl.java:412)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.UndoManagerImpl.b(UndoManagerImpl.java:424)
	at com.intellij.openapi.command.impl.UndoManagerImpl.undo(UndoManagerImpl.java:392)
	at com.intellij.ide.actions.UndoAction.perform(UndoAction.java:30)
	at com.intellij.ide.actions.UndoRedoAction.actionPerformed(UndoRedoAction.java:39)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by donkirkby** [comment]
I think this might get fixed if I move the analysis to a timer, as it's done in the Eclipse version. That might also fix #133.
