### ISSUE TITLE
Reporting failure with infinite loop and yield from

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#125]
Something is strange about the `yield from` statement. It messes up the reporting of an infinite loop.

Here's a simple example with the `yield from` commented out, and the message limit set to 10.

    def a():                   | 
        yield 1                | 
                               | 
    def b():                   | 
        for i in range(10000): | i = 0   | i = 1   | i = 2   | i = 3   | i = 4 
            yield 2            | yield 2 | yield 2 | yield 2 | yield 2 | RuntimeError: live coding message limit exceeded 
            # yield from a()   | 
                               | 
    try:                       | 
        for x in b():          | x = 2 | x = 2 | x = 2 | x = 2 
            pass               |       |       |       | 
    except RuntimeError as x:  | x = RuntimeError('live coding message limit exceeded',) 
        pass                   | 

When I uncomment the `yield from`, I get this:

```
Traceback (most recent call last):
  File "/home/don/git/live-py-plugin/plugin/PySrc/code_tracer.py", line 1027, in <module>
    main()
  File "/home/don/git/live-py-plugin/plugin/PySrc/code_tracer.py", line 1015, in main
    filename=args.filename)
  File "/home/don/git/live-py-plugin/plugin/PySrc/code_tracer.py", line 926, in trace_code
    report = builder.report()
  File "/mnt/data/don/git/live-py-plugin/plugin/PySrc/report_builder.py", line 197, in report
    self.start_block(first_line, last_line)
  File "/mnt/data/don/git/live-py-plugin/plugin/PySrc/report_builder.py", line 41, in start_block
    self._increment_message_count()
  File "/mnt/data/don/git/live-py-plugin/plugin/PySrc/report_builder.py", line 88, in _increment_message_count
    raise RuntimeError('live coding message limit exceeded')
RuntimeError: live coding message limit exceeded

```

**Comment by donkirkby** [comment]
While I'm looking at `yield from`, it might be useful to display the contents that were yielded.

For example, this is the current display:

    def a():              |           |           |           | 
       yield 'x'          | yield 'x' | yield 'x' | yield 'x' | yield 'x' 
       yield 'y'          | yield 'y' | yield 'y' | yield 'y' | yield 'y' 
                          | 
                          | 
    def b():              | 
       for i in range(2): | i = 0 | i = 1 
          yield from a()  |       | 
                          | 
                          | 
    def c():              | 
       for i in range(2): | i = 0                 | i = 1 
          for x in a():   | x = 'x'   | x = 'y'   | x = 'x'   | x = 'y' 
             yield x      | yield 'x' | yield 'y' | yield 'x' | yield 'y' 
                          | 
                          | 
    l = list(b())         | l = ['x', 'y', 'x', 'y'] 
    l = list(c())         | l = ['x', 'y', 'x', 'y'] 

What if `b()` displayed the contents of the `yield from`?

    def a():              |           |           |           | 
       yield 'x'          | yield 'x' | yield 'x' | yield 'x' | yield 'x' 
       yield 'y'          | yield 'y' | yield 'y' | yield 'y' | yield 'y' 
                          | 
                          | 
    def b():              | 
       for i in range(2): | i = 0                 | i = 1 
          yield from a()  | yield 'x' | yield 'y' | yield 'x' | yield 'y' 
                          | 
                          | 
    def c():              | 
       for i in range(2): | i = 0                 | i = 1 
          for x in a():   | x = 'x'   | x = 'y'   | x = 'x'   | x = 'y' 
             yield x      | yield 'x' | yield 'y' | yield 'x' | yield 'y' 
                          | 
                          | 
    l = list(b())         | l = ['x', 'y', 'x', 'y'] 
    l = list(c())         | l = ['x', 'y', 'x', 'y'] 

Maybe this should be a separate issue.
