### ISSUE TITLE
Error: Python is not a recognized command

### ISSUE THREAD

**Issue by salvor7** [donkirkby/live-py-plugin#188]
I'm receiving the following IDE Fatal Error when trying to run the live coding plugin. (My system details follow)

Couldn't read virtualenv variables: rv:1 text:0 out:'"C:\Users\username\AppData\Local\Temp\..\python.exe"' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
java.lang.Exception: rv:1 text:0 out:'"C:\Users\username\AppData\Local\Temp\..\python.exe"' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.

	at com.intellij.util.EnvironmentUtil$ShellEnvReader.runProcessAndReadEnvs(EnvironmentUtil.java:231)
	at com.intellij.util.EnvironmentUtil$ShellEnvReader.runProcessAndReadEnvs(EnvironmentUtil.java:207)
	at com.intellij.util.EnvironmentUtil$ShellEnvReader.runProcessAndReadEnvs(EnvironmentUtil.java:199)
	at com.jetbrains.python.run.PyVirtualEnvReader.access$runProcessAndReadEnvs$s-1783813152(PyVirtualEnvReader.kt:31)
	at com.jetbrains.python.run.PyVirtualEnvReader.readVirtualEnvOnWindows(PyVirtualEnvReader.kt:85)
	at com.jetbrains.python.run.PyVirtualEnvReader.readShellEnv(PyVirtualEnvReader.kt:61)
	at com.jetbrains.python.run.PythonCommandLineState.setupVirtualEnvVariables(PythonCommandLineState.java:346)
	at com.jetbrains.python.run.PythonCommandLineState.initEnvironment(PythonCommandLineState.java:330)
	at com.jetbrains.python.run.PythonCommandLineState.createPythonCommandLine(PythonCommandLineState.java:292)
	at com.jetbrains.python.run.PythonCommandLineState.generateCommandLine(PythonCommandLineState.java:275)
	at com.jetbrains.python.run.PythonCommandLineState.generateCommandLine(PythonCommandLineState.java:261)
	at io.github.donkirkby.livepycharm.LiveCodingAnalyst.lambda$startProcess$5(LiveCodingAnalyst.java:385)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:953)
	at io.github.donkirkby.livepycharm.LiveCodingAnalyst.startProcess(LiveCodingAnalyst.java:383)
	at io.github.donkirkby.livepycharm.LiveCodingAnalyst.getDisplay(LiveCodingAnalyst.java:303)
	at io.github.donkirkby.livepycharm.LiveCodingAnalyst.analyse(LiveCodingAnalyst.java:231)
	at io.github.donkirkby.livepycharm.LiveCodingAnalyst.lambda$null$2(LiveCodingAnalyst.java:323)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

System:
Windows 10
PyCharm Community Edition 2017.2.3
Anaconda Python 3.6.3
Live Coding in Python 2.21.1

**Comment by donkirkby** [comment]
Is this the same system that you got working at the sprint day?

**Comment by salvor7** [comment]
This error actually came up while at the sprint. I ended up working on the
bugs without having the plugin work for me.

Andrew Brown

**Comment by donkirkby** [comment]
OK, I'll try to set up the same tools that you're using. Thanks for the bug report.

**Comment by donkirkby** [comment]
I installed Anaconda 1.6.9 with Python 3.6.3 on Windows 10, and it all works fine with PyCharm 2017.3.3 and Live Coding in Python 2.21.1.

Can you tell me all the equivalent versions for your setup? Can you run this script, please?

    import sys
    
    print(sys.version_info)

Then copy and paste the whole output window here. Here's what I saw in my output window:

    C:\Users\don\Anaconda3\python.exe "C:/Users/don/PycharmProjects/another junkyard/another junkyard.py"
    sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
    
    Process finished with exit code 0

**Comment by salvor7** [comment]
Here is what I saw
C:\Anaconda3\python.exe C:/Users/salvor7/PycharmProjects/trylivecoding/debug.py
sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)

**Comment by salvor7** [comment]
It seems though that the problem has gone away. I've tried to reproduce the error, and no "luck". I'll see if it comes back, and log more error messages if it does.
