### ISSUE TITLE
Redirect stdin

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#215]
# What I did
I used the option in PyCharm's run configuration to redirect stdin from a file. Then I used that run configuration to launch live coding.

# What happened
PyCharm complained that there was an error, and only displayed `null`.

```
Report failed.

java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.OutputStream.write(OutputStream.java:75)
	at io.github.donkirkby.livepycharm.LiveCodingAnalyst.startProcess(LiveCodingAnalyst.java:403)
	at io.github.donkirkby.livepycharm.LiveCodingAnalyst.getDisplay(LiveCodingAnalyst.java:311)
	at io.github.donkirkby.livepycharm.LiveCodingAnalyst.analyse(LiveCodingAnalyst.java:240)
	at io.github.donkirkby.livepycharm.LiveCodingAnalyst.lambda$null$2(LiveCodingAnalyst.java:331)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
I think the `LiveCodingAnalyst` is unable to write the source code to the process's stdin when it has been redirected. Possible solutions: pass an option for a file name to redirect stdin from, or write the source code to a temp file, and pass the temp file as the source code instead of stdin.

# What I wanted to happen
I wanted to be able to use `input()` in a script, so I wanted the standard input to come from the redirected file.

# My environment
Describe the versions of everything you were using:
* PyCharm 2018.3.1
* Ubuntu 18.04
* Python 3.6

**Comment by donkirkby** [comment]
I found a related problem in the new browser version. Reading from stdin pops up a prompt dialog. Here are some examples that pop up the dialog:

```
x = input()
```

```
f = open('/dev/stdin')
s = f.read()
```
```
f = open('/dev/stdout')
s = f.read()
```
```
import sys
s = sys.stdin.read()
```

The browser version should default to an empty stdin, and allow stdin text to be passed as a parameter.
