### ISSUE TITLE
Starred assignment in for loop

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#232]
# What I did
Unpacked items into a starred list as part of a for loop.

    words = ['apple', 'banana']
    for (head, *tail) in words:
        print(head, tail)

# What happened
When I run the script, it works as expected:

    a ['p', 'p', 'l', 'e']
    b ['a', 'n', 'a', 'n', 'a']

However, the live coding display shows the error, "TypeError: 'Starred' object is not iterable."

    words = ['apple', 'banana'] | ------------------------------------------------------------------------------------------------------ | 
    for (head, *tail) in words: | Traceback (most recent call last):                                                                     | 
        print(head, tail)       |   File "/home/don/git/live-py-plugin/plugin/PySrc/code_tracer.py", line 584, in _trace_assignment_list | 
                                |     todo = list(todo)                                                                                  | 
                                | TypeError: 'Starred' object is not iterable                                                            | 
                                |                                                                                                        | 
                                | During handling of the above exception, another exception occurred:                                    | 
                                |                                                                                                        | 
                                | Traceback (most recent call last):                                                                     | 
                                |   File "/usr/lib/python3.6/ast.py", line 253, in visit                                                 | 
                                |     return visitor(node)                                                                               | 
                                |   File "/home/don/git/live-py-plugin/plugin/PySrc/code_tracer.py", line 484, in visit_Module           | 
                                |     new_node = self.generic_visit(node)                                                                | 
                                |   File "/usr/lib/python3.6/ast.py", line 308, in generic_visit                                         | 
                                |     value = self.visit(value)                                                                          | 
                                |   File "/home/don/git/live-py-plugin/plugin/PySrc/code_tracer.py", line 95, in visit                   | 
                                |     new_node = super(Tracer, self).visit(node)                                                         | 
                                |   File "/usr/lib/python3.6/ast.py", line 253, in visit                                                 | 
                                |     return visitor(node)                                                                               | 
                                |   File "/home/don/git/live-py-plugin/plugin/PySrc/code_tracer.py", line 389, in visit_For              | 
                                |     new_body.extend(self._trace_assignment_list(new_node.target))                                      | 
                                |   File "/home/don/git/live-py-plugin/plugin/PySrc/code_tracer.py", line 592, in _trace_assignment_list | 
                                |     new_nodes.extend(self._trace_assignment_list(target))                                              | 
                                |   File "/home/don/git/live-py-plugin/plugin/PySrc/code_tracer.py", line 587, in _trace_assignment_list | 
                                |     trace = self._trace_assignment(targets)                                                            | 
                                |   File "/home/don/git/live-py-plugin/plugin/PySrc/code_tracer.py", line 604, in _trace_assignment      | 
                                |     assert isinstance(target, str), assert_message                                                     | 
                                | AssertionError: Target type was <class '_ast.Starred'>.                                                | 
                                | ------------------------------------------------------------------------------------------------------ | 

# What I wanted to happen
The same display as is used when you're not in a for loop:

    words = ['apple', 'banana'] | words = ['apple', 'banana']
    for (head, *tail) in words: | (head, *tail) = ('a', 'p', 'p', 'l', 'e') | (head, *tail) = ('b', 'a', 'n', 'a', 'n', 'a')
        print(head, tail)       | print("a ['p', 'p', 'l', 'e']")           | print("b ['a', 'n', 'a', 'n', 'a']") 

# My environment
Describe the versions of everything you were using:
* PyCharm 2019.2
* Ubuntu 18.04
* Python 3.6.8

**Comment by donkirkby** [comment]
Might be related:

    class Foo:                      | ------------------------------------------------------------------- | 
        def do_foo(self, x):        | Traceback (most recent call last):                                  | 
            for self.i in range(x): |   File "code_tracer.py", line 584, in _trace_assignment_list        | 
                print(self.i)       |     todo = list(todo)                                               | 
                                    | TypeError: 'Attribute' object is not iterable                       | 
    foo = Foo()                     |                                                                     | 
    foo.do_foo(3)                   | During handling of the above exception, another exception occurred: | 
                                    |                                                                     | 
                                    | Traceback (most recent call last):                                  | 
                                    |   File "/usr/lib/python3.6/ast.py", line 253, in visit              | 
                                    |     return visitor(node)                                            | 
                                    |   File "code_tracer.py", line 484, in visit_Module                  | 
                                    |     new_node = self.generic_visit(node)                             | 
                                    |   File "/usr/lib/python3.6/ast.py", line 308, in generic_visit      | 
                                    |     value = self.visit(value)                                       | 
                                    |   File "code_tracer.py", line 95, in visit                          | 
                                    |     new_node = super(Tracer, self).visit(node)                      | 
                                    |   File "/usr/lib/python3.6/ast.py", line 253, in visit              | 
                                    |     return visitor(node)                                            | 
                                    |   File "/usr/lib/python3.6/ast.py", line 308, in generic_visit      | 
                                    |     value = self.visit(value)                                       | 
                                    |   File "code_tracer.py", line 95, in visit                          | 
                                    |     new_node = super(Tracer, self).visit(node)                      | 
                                    |   File "/usr/lib/python3.6/ast.py", line 253, in visit              | 
                                    |     return visitor(node)                                            | 
                                    |   File "code_tracer.py", line 418, in visit_FunctionDef             | 
                                    |     new_node = self.generic_visit(node)                             | 
                                    |   File "/usr/lib/python3.6/ast.py", line 308, in generic_visit      | 
                                    |     value = self.visit(value)                                       | 
                                    |   File "code_tracer.py", line 95, in visit                          | 
                                    |     new_node = super(Tracer, self).visit(node)                      | 
                                    |   File "/usr/lib/python3.6/ast.py", line 253, in visit              | 
                                    |     return visitor(node)                                            | 
                                    |   File "code_tracer.py", line 389, in visit_For                     | 
                                    |     new_body.extend(self._trace_assignment_list(new_node.target))   | 
                                    |   File "code_tracer.py", line 587, in _trace_assignment_list        | 
                                    |     trace = self._trace_assignment(targets)                         | 
                                    |   File "code_tracer.py", line 604, in _trace_assignment             | 
                                    |     assert isinstance(target, str), assert_message                  | 
                                    | AssertionError: Target type was <class '_ast.Attribute'>.           | 
                                    | ------------------------------------------------------------------- |
