### ISSUE TITLE
Installing space-tracer from sdist fails

### ISSUE THREAD

**Issue by jayvdb** [donkirkby/live-py-plugin#255]
When installing using https://files.pythonhosted.org/packages/0c/cd/9d1621f6ab30a962c151ec4d5f8afb8dfa7f3310ce5c50d1ef24d488ed7c/space_tracer-3.0.0.tar.gz

```py
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    with open("space_tracer.md") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'space_tracer.md'
```

btw it is such a crazy innovative idea in itself, space-tracer should be a separate repo IMO.  I could see a pytest plugin using it being very useful for debugging test failures that only occur on isolated VMs (e.g. rpm build workers) and dont want to be reproduced locally.

**Comment by donkirkby** [comment]
Thanks for the kind words, and for trying out my project.

### Steps to Reproduce
I was able to reproduce your error with the following steps. Please let me know if you did something different.

1. Go to the package page on [PyPI], and copy the address of the source distribution.
2. Download the archive, and try to install it with `pip`.

```
$ wget https://files.pythonhosted.org/packages/0c/cd/9d1621f6ab30a962c151ec4d5f8afb8dfa7f3310ce5c50d1ef24d488ed7c/space_tracer-3.0.0.tar.gz
[...]
2020-01-12 08:52:36 (728 KB/s) - ‘space_tracer-3.0.0.tar.gz’ saved [32281/32281]
$ pip install space_tracer-3.0.0.tar.gz 
Processing ./space_tracer-3.0.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/don/workspace/inst_test/venv_inst_test/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-5rz1s5s4/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-5rz1s5s4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-5rz1s5s4/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-5rz1s5s4/setup.py", line 3, in <module>
        with open("space_tracer.md") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'space_tracer.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
$ 
```

### Analysis
I suspect I need to include the extra markdown file with a [manifest template].

### Workaround
Clone the repository and install from there.

    $ git clone --branch v3.0.0 https://github.com/donkirkby/live-py-plugin.git
    $ pip install live-py-plugin/
    $ rm -rf live-py-plugin/

### Discussion
I thought about moving space tracer to a separate repository, but I couldn't come up with any reason to justify duplicating the source code. It might be a little confusing to have it mixed in with the other plugins, but this way they all get released together whenever I make improvements. Does it cause you any trouble to have it mixed in with the Live Coding in Python project?

As for Pytest, you don't need a specific plugin. You can already run Pytest under Space Tracer. Here's an example with your `crosslink` repository:

```
$ space_tracer --traced crosslink.resolve -m pytest tests/test_github.py::TestGitHub::test_email_lookup
def resolve(haves, services):                          | services = [<crosslink.services.github.GitHubService object at 0x7f10526f7208>]
    if not isinstance(haves, list):                    |
        haves = [haves]                                | haves = [<crosslink.identifiers.Email object at 0x7f10526f7128>]
                                                       |
    not_processed = haves[:]                           | not_processed = [<crosslink.identifiers.Email object at 0x7f10526f7128>]
                                                       |
    while not_processed:                               |                                                                                                                                                                                                                                                                                                          |                                                                                                   |                                                                                                  |                                                                                       |
        current = not_processed.pop()                  | not_processed = []                                                                                                                                                                                                                                                                                       | not_processed = [<crosslink.services.github.GitHubI[131 chars]dAccount object at 0x7f10526f75f8>] | not_processed = [<crosslink.services.github.GitHubI[65 chars]dAccount object at 0x7f10526f74a8>] | not_processed = [<crosslink.services.github.GitHubIdentity object at 0x7f10527b0710>] | not_processed = []
        if isinstance(current, Account):               |                                                                                                                                                                                                                                                                                                          |                                                                                                   |                                                                                                  |                                                                                       |
            current_item = current                     |                                                                                                                                                                                                                                                                                                          |                                                                                                   |                                                                                                  |                                                                                       |
        elif isinstance(current, VerifiedAccount):     |                                                                                                                                                                                                                                                                                                          |                                                                                                   |                                                                                                  |                                                                                       |
            current_item = current.account             |                                                                                                                                                                                                                                                                                                          |                                                                                                   |                                                                                                  |                                                                                       |
        else:                                          |                                                                                                                                                                                                                                                                                                          |                                                                                                   |                                                                                                  |                                                                                       |
            current_item = current                     |                                                                                                                                                                                                                                                                                                          |                                                                                                   |                                                                                                  |                                                                                       |
        for service in services:                       |                                                                                                                                                                                                                                                                                                          |                                                                                                   |                                                                                                  |                                                                                       |
            new = service.get_identity(current_item)   |                                                                                                                                                                                                                                                                                                          |                                                                                                   | new = None                                                                                       |                                                                                       | new = None
            if new:                                    |                                                                                                                                                                                                                                                                                                          |                                                                                                   |                                                                                                  |                                                                                       |
                if new not in haves:                   |                                                                                                                                                                                                                                                                                                          |                                                                                                   |                                                                                                  |                                                                                       |
                    haves.append(new)                  | haves = [<crosslink.identifiers.Email objec[55 chars]Identity object at 0x7f10527b0710>]                                                                                                                                                                                                                 |                                                                                                   |                                                                                                  |                                                                                       |
                    not_processed.append(new)          | not_processed = [<crosslink.services.github.GitHubIdentity object at 0x7f10527b0710>]                                                                                                                                                                                                                    |                                                                                                   |                                                                                                  |                                                                                       |
                if hasattr(new, 'get_fragments'):      |                                                                                                                                                                                                                                                                                                          |                                                                                                   |                                                                                                  |                                                                                       |
                    for item in new.get_fragments():   |                                                                                                  |                                                                                                   |                                                                                                   |                                                                                                   |                                                                                                  |                                                                                       |
                        if item not in haves:          |                                                                                                  |                                                                                                   |                                                                                                   |                                                                                                   |                                                                                                  |                                                                                       |
                            haves.append(item)         | haves = [<crosslink.identifiers.Email objec[121 chars]dAccount object at 0x7f10526f74a8>]        | haves = [<crosslink.identifiers.Email objec[187 chars]dAccount object at 0x7f10526f75f8>]         | haves = [<crosslink.identifiers.Email objec[253 chars]dAccount object at 0x7f10527b0470>]         |                                                                                                   |                                                                                                  |                                                                                       |
                            not_processed.append(item) | not_processed = [<crosslink.services.github.GitHubI[65 chars]dAccount object at 0x7f10526f74a8>] | not_processed = [<crosslink.services.github.GitHubI[131 chars]dAccount object at 0x7f10526f75f8>] | not_processed = [<crosslink.services.github.GitHubI[197 chars]dAccount object at 0x7f10527b0470>] |                                                                                                   |                                                                                                  |                                                                                       |
                                                       |
    return haves                                       | return [<crosslink.identifiers.Email objec[253 chars]dAccount object at 0x7f10527b0470>]
```

[PyPI]: https://pypi.org/project/space-tracer/#files
[manifest template]: https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute

**Comment by donkirkby** [comment]
This should be fixed in the next release, thanks for reporting the problem.

By the way, how did you learn about the project? Have you found it useful?

**Comment by jayvdb** [comment]
@donkirkby 
I found it by googling/githubbing(the horrid search of github makes this time consuming but often fruitful).

One way you could improve that is to ensure that a name search filtered by Python projects https://github.com/search?l=Python&q=space-tracer&type=Repositories includes this repo, as currently the only hit is https://github.com/vainia/Disk_Space_Tracer

https://github.com/search?l=Python&q=live+coding&type=Repositories does include this repo, so simply adding "space-tracer" to the repo metadata (description, tags, etc) should ensure that people can re-find this repo if they know the name.

Ideally it should appear also in https://github.com/search?l=Python&q=trace&type=Repositories

I would expect that splitting it off to a separate repo would not result in duplication.  A git submodule / subtree would be one approach, if nothing else is suitable.

I can appreciate keeping it all together is a bit easier.  One reason to split it would be to make it easier to fetch and test just the core library, however https://github.com/donkirkby/live-py-plugin/pull/263 would mostly fix that.

The other more convincing reason is that there are increasingly tools like @dephell which peek into the source repos and expect to find the installed components either in the root or `src`.  I recently enhanced its parser of `setup.py` , so it could be improved to recognise other layouts, but there are many other parts of it that need to be enhanced to actually support other layouts.

Regarding usefulness, I'd like to see it wrapped up in a pytest plugin, which will make it more accessible, being simpler to use, and also lots of Python IDE's already integrate/wrap pytest reasonably well.
