### ISSUE TITLE
Support Python 3.7 features

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#257]
# What I did
Tried using a data class.

```
from dataclasses import dataclass


@dataclass
class Point:
    x: float


p = Point(1)
print(p)
```

# What happened
Some internal error.

```
$ space_tracer scratch.py
from dataclasses import dataclass | ---------------------------------------------- |
                                  | ValueError: None disallowed in expression list |
                                  | ---------------------------------------------- |
@dataclass                        |
class Point:                      |
    x: float                      |
                                  |
                                  |
p = Point(1)                      |
print(p)                          |
$
```

# What I wanted to happen
It should display the code with the data classes default representation.

# My environment
* Space Tracer 3.0.0
* Ubuntu 18.04
* Python 3.7.6

[Features] from Python 3.7 to try:

* [x] data classes
* [x] ~~`async` and `await`?~~ moved to #258
* [x] context variables

[Features]: https://docs.python.org/3/whatsnew/3.7.html

**Comment by donkirkby** [comment]
Some trouble with `async` and `await`. It looks like my handling of `yield from` doesn't play well with asynchronous generators.

Here's an example of the problem:

```
$ space_tracer scratch.py
import asyncio                                                        |
                                                                      |
# Borrowed from http://curio.readthedocs.org/en/latest/tutorial.html. |
@asyncio.coroutine                                                    |                                                     |
def countdown(number, n):                                             | number = 'A' | n = 2                                | number = 'B' | n = 3
    while n > 0:                                                      |                                                     |
        print('T-minus', n, '({})'.format(number))                    | print('T-minus 2 (A)')                              | print('T-minus 3 (B)')
        x = asyncio.sleep(1)                                          |                                                     |
        print(x)                                                      | print('<coroutine object sleep at 0x7fdbf6df3440>') | print('<coroutine object sleep at 0x
        yield from x                                                  | TypeError: 'coroutine' object is not iterable       | TypeError: 'coroutine' object is not
        n -= 1                                                        |                                                     |
                                                                      |
loop = asyncio.get_event_loop()                                       |
tasks = [                                                             | tasks = [<Task pending coro=<countdown() ru[48 chars]ntdown() running at scratch.py:4>>]
    asyncio.ensure_future(countdown("A", 2)),                         |
    asyncio.ensure_future(countdown("B", 3))]                         |
loop.run_until_complete(asyncio.wait(tasks))                          |
loop.close()                                                          | loop = <_UnixSelectorEventLoop running=False closed=True debug=False>
Task exception was never retrieved
future: <Task finished coro=<countdown() done, defined at scratch.py:4> exception=TypeError("'coroutine' object is not iterable")>
Traceback (most recent call last):
  File "scratch.py", line 10, in countdown
    yield from x
  File "/home/don/.local/share/virtualenvs/scratch-jH7kJ-ke/lib/python3.7/site-packages/space_tracer/report_builder.py", line 301, in yield_from
    for value in values:
TypeError: 'coroutine' object is not iterable
Task exception was never retrieved
future: <Task finished coro=<countdown() done, defined at scratch.py:4> exception=TypeError("'coroutine' object is not iterable")>
Traceback (most recent call last):
  File "scratch.py", line 10, in countdown
    yield from x
  File "/home/don/.local/share/virtualenvs/scratch-jH7kJ-ke/lib/python3.7/site-packages/space_tracer/report_builder.py", line 301, in yield_from
    for value in values:
TypeError: 'coroutine' object is not iterable
sys:1: RuntimeWarning: coroutine 'sleep' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by donkirkby** [comment]
It's happier when I convert to `async` and `await`.

```
$ space_tracer scratch.py
import asyncio                                                        |
                                                                      |
# Borrowed from http://curio.readthedocs.org/en/latest/tutorial.html. |
async def countdown(number, n):                                       |
    while n > 0:                                                      |       |       |               |
        print('T-minus', n, '({})'.format(number))                    |       |       |               |
        x = asyncio.sleep(1)                                          |       |       |               |
        # print(x)                                                    |       |       |               |
        await x                                                       |       |       |               |
        n -= 1                                                        | n = 1 | n = 2 | n = 0 | n = 1 | n = 0
                                                                      |
loop = asyncio.get_event_loop()                                       |
tasks = [                                                             | tasks = [<Task pending coro=<countdown() ru[48 chars]ntdown() running at scratch.py:4>>]
    asyncio.ensure_future(countdown("A", 2)),                         |
    asyncio.ensure_future(countdown("B", 3))]                         |
loop.run_until_complete(asyncio.wait(tasks))                          | print('T-minus 2 (A)') print('T-minus 3 (B)') print('T-minus 1 (A)') print('T-minus 2 (B)'
loop.close()                                                          | loop = <_UnixSelectorEventLoop running=False closed=True debug=False>
$
```
Still not perfect, though.

* The print output doesn't appear in the `countdown()` function, only in the outer scope. Maybe there's something weird about the stack frame.
* The function parameters aren't displayed.
* Because the two while loops are happening simultaneously, the last iteration of the first loop isn't fully separated from the next iteration of the other loop.

**Comment by donkirkby** [comment]
We could display the contents of context variables, but I'm not sure it's worth the effort. Closing for now.
