### ISSUE TITLE
Missing tkinter breaks plugin

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#430]
## What I did
Switched to a Python interpreter that doesn't include tkinter support. This only seems to happen when developing in IDEA, not in PyCharm.

## What happened
Error message:

```
Live coding plugin error:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/don/.cache/JetBrains/IntelliJIdea2020.1/plugins-sandbox/plugins/livepy/classes/space_tracer/__init__.py", line 6, in <module>
    from .live_image import (LivePng, LivePillowImage, LiveImageDiffer,
  File "/home/don/.cache/JetBrains/IntelliJIdea2020.1/plugins-sandbox/plugins/livepy/classes/space_tracer/live_image.py", line 10, in <module>
    from space_tracer.mock_turtle import MockTurtle
  File "/home/don/.cache/JetBrains/IntelliJIdea2020.1/plugins-sandbox/plugins/livepy/classes/space_tracer/mock_turtle.py", line 23, in <module>
    from turtle import RawTurtle, TurtleScreen, TurtleGraphicsError
  File "/usr/lib/python3.7/turtle.py", line 116, in <module>
    from tkinter import simpledialog
ImportError: cannot import name 'simpledialog' from 'tkinter' (unknown location)
```

## What I wanted to happen
Should continue faking enough of tkinter support to run live coding.

## My environment
Describe the versions of everything you were using:
* PyCharm 
* Live Coding plugin 4.8.0
* Ubuntu 20.04
* Python 3.7 (without tkinter support)

**Comment by donkirkby** [comment]
Can't reproduce. Closing.
